//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Квартира.
    /// </summary>
    // *** Start programmer edit section *** (Квартира CustomAttributes)

    // *** End programmer edit section *** (Квартира CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КвартираE", new string[] {
            "Номер as \'Номер\'"})]
    [View("КвартираL", new string[] {
            "Номер as \'Номер\'"})]
    public class Квартира : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fВоПад;
        
        // *** Start programmer edit section *** (Квартира CustomMembers)

        // *** End programmer edit section *** (Квартира CustomMembers)

        
        /// <summary>
        /// ВоПад.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.ВоПад CustomAttributes)

        // *** End programmer edit section *** (Квартира.ВоПад CustomAttributes)
        private int ВоПад
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.ВоПад Get start)

                // *** End programmer edit section *** (Квартира.ВоПад Get start)
                int result = this.fВоПад;
                // *** Start programmer edit section *** (Квартира.ВоПад Get end)

                // *** End programmer edit section *** (Квартира.ВоПад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.ВоПад Set start)

                // *** End programmer edit section *** (Квартира.ВоПад Set start)
                this.fВоПад = value;
                // *** Start programmer edit section *** (Квартира.ВоПад Set end)

                // *** End programmer edit section *** (Квартира.ВоПад Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.Номер CustomAttributes)

        // *** End programmer edit section *** (Квартира.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.Номер Get start)

                // *** End programmer edit section *** (Квартира.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Квартира.Номер Get end)

                // *** End programmer edit section *** (Квартира.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.Номер Set start)

                // *** End programmer edit section *** (Квартира.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Квартира.Номер Set end)

                // *** End programmer edit section *** (Квартира.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КвартираE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираE", typeof(IIS.Proba_3.Квартира));
                }
            }
            
            /// <summary>
            /// "КвартираL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираL", typeof(IIS.Proba_3.Квартира));
                }
            }
        }
    }
}
