//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Улица.
    /// </summary>
    // *** Start programmer edit section *** (Улица CustomAttributes)

    // *** End programmer edit section *** (Улица CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УлицаE", new string[] {
            "Наименование as \'Наименование\'",
            "Квартира as \'Квартира\'",
            "Квартира.Номер as \'Номер\'"}, Hidden=new string[] {
            "Квартира.Номер"})]
    [MasterViewDefineAttribute("УлицаE", "Квартира", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("УлицаL", new string[] {
            "Наименование as \'Наименование\'",
            "Квартира.Номер as \'Номер\'"})]
    public class Улица : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.Proba_3.Квартира fКвартира;
        
        // *** Start programmer edit section *** (Улица CustomMembers)

        // *** End programmer edit section *** (Улица CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Улица.Наименование CustomAttributes)

        // *** End programmer edit section *** (Улица.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Улица.Наименование Get start)

                // *** End programmer edit section *** (Улица.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Улица.Наименование Get end)

                // *** End programmer edit section *** (Улица.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Улица.Наименование Set start)

                // *** End programmer edit section *** (Улица.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Улица.Наименование Set end)

                // *** End programmer edit section *** (Улица.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Улица.
        /// </summary>
        // *** Start programmer edit section *** (Улица.Квартира CustomAttributes)

        // *** End programmer edit section *** (Улица.Квартира CustomAttributes)
        [PropertyStorage(new string[] {
                "Квартира"})]
        [NotNull()]
        public virtual IIS.Proba_3.Квартира Квартира
        {
            get
            {
                // *** Start programmer edit section *** (Улица.Квартира Get start)

                // *** End programmer edit section *** (Улица.Квартира Get start)
                IIS.Proba_3.Квартира result = this.fКвартира;
                // *** Start programmer edit section *** (Улица.Квартира Get end)

                // *** End programmer edit section *** (Улица.Квартира Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Улица.Квартира Set start)

                // *** End programmer edit section *** (Улица.Квартира Set start)
                this.fКвартира = value;
                // *** Start programmer edit section *** (Улица.Квартира Set end)

                // *** End programmer edit section *** (Улица.Квартира Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УлицаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УлицаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УлицаE", typeof(IIS.Proba_3.Улица));
                }
            }
            
            /// <summary>
            /// "УлицаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УлицаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УлицаL", typeof(IIS.Proba_3.Улица));
                }
            }
        }
    }
}
